# 当前环境配置，可选值: prod, uat, dev
current_env: prod

# 环境配置
environments:
  prod:
    database:
      host: "APCHALIVPPOS06"
      port: 3306
      name: "datahub"
      username: "datahub"
      password: "4rfvBGT#6yhn"
    sqlserver:
      host: "apchalivpxcdb01"
      port: 1433
      name: "xcenter"
      username: "sa"
      password: "Xstore123"
    api:
      timeout: 30
      retries: 3

  uat:
    database:
      host: "APCHALIVQPOS06"
      port: 3306
      name: "datahub"
      username: "datahub"
      password: "4rfvBGT#6yhn"
    sqlserver:
      host: "apchalivpxcdb01"
      port: 1433
      name: "xcenter"
      username: "sa"
      password: "Xstore123"
    api:
      timeout: 30
      retries: 3

